### ISSUE TITLE
Giphy message not being displayed

### ISSUE THREAD

**Issue by tiagostutz** [slack-samples/deno-give-kudos#34]
Hi.!
I'm using this project as a template to implement my own bot and during the tests I couldn't make the gif from giphy links to be rendered. I tried sending as is in the tutorial and tried also sending two separated messages, being one with the giphy itself and no luck. If I just copy and paste the URL myself and send, it works, as you can see in the screenshot:

<img width="726" alt="Screenshot 2024-04-01 at 22 30 39" src="https://github.com/slack-samples/deno-give-kudos/assets/3986989/963869a8-82c8-456c-b6fb-66d337208c5a">

In the screenshot:
1) Message with the text and GIF link in the one message. Not displaying.
2) Message with the text in one message and GIF link on another message. Not displaying.
3) My manual sent message, just copying and pasting the link. Displaying.

Tried both "local" and "deployed" versions

Maybe any configuration I'm missing?

**Comment by zimeg** [comment]
Hey @tiagostutz 👋  Thank you for sharing this! The underlying Block Kit formatting seems to have changed and we hadn't caught this yet 🤦
